shoes_mag/niker/urls.py
from django.urls import path

from .views import ShoesView, FilterShoes, ShoesDetail, AddOrder, CategoryView, Search

urlpatterns = [
    path('', ShoesView.as_view(), name='home'),
    path('shoes/<slug:slug>', ShoesDetail.as_view(), name='shoes_detail'),
    path('category/<slug:slug>', CategoryView.as_view(), name = 'category'),
    path('filter-shoes', FilterShoes.as_view(), name='filter'),
    path('addorder/<int:pk>', AddOrder.as_view(), name='addorder'),
    path('shoes/', Search.as_view(), name='search')
]

shoes_mag/shoes_mag/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shoes_mag import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('niker.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoes_mag/niker/models.py
from django.db import models
from django.urls import reverse


class ShoesCategory(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(unique=True, db_index=True, verbose_name='Url')

    class Meta:
        verbose_name = 'Категория обуви'
        verbose_name_plural = 'Категории обуви'

    def __str__(self):
            return f'{self.id}. {self.title}'

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})

class ShoesSize(models.Model):
    size = models.SmallIntegerField(default=0, verbose_name='Размер обуви')

    class Meta:
        verbose_name = 'Размер обуви'
        verbose_name_plural = 'Размеры обуви'

    def __str__(self):
        return f'Размер: {self.size}'

class Shoes(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название обуви')
    img = models.ImageField(upload_to='shoes/%Y/%m/%d', verbose_name='Фото')
    price = models.SmallIntegerField(default=0, verbose_name='Цена')
    color = models.CharField(max_length=255, verbose_name='Цвет обуви')
    size = models.ManyToManyField(ShoesSize, verbose_name='Размер')
    slug = models.SlugField(unique=True, db_index=True, verbose_name='Url')
    category = models.ForeignKey(ShoesCategory, on_delete=models.PROTECT, verbose_name='Категория обуви')

    class Meta:
        verbose_name = 'Обувь'
        verbose_name_plural = 'Обуви'

    def __str__(self):
        return f'{self.id}. {self.title}'

    def get_absolute_url(self):
        return reverse('shoes_detail', kwargs={'slug': self.slug})

class ShoesPhoto(models.Model):
    img = models.ImageField(upload_to='shoes_photo/%Y/%m/%d', verbose_name='Дополнительные фото')
    shoes = models.ForeignKey(Shoes, on_delete=models.CASCADE, verbose_name='Обувь')

    class Meta:
        verbose_name = 'Дополнительное фото'
        verbose_name_plural = 'Дополнительные фото'



class Order(models.Model):
    shoes = models.ForeignKey(Shoes, on_delete=models.PROTECT,verbose_name='Обувь')
    name = models.CharField(max_length=255, verbose_name='Имя покупателя')
    number = models.CharField(max_length=255, verbose_name='Номер')
    address= models.CharField(max_length=255, verbose_name='Адресс')

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

shoes_mag/niker/forms.py
from django import forms

from .models import *


class OrderForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Order
        fields = ('name', 'number', 'address')

shoes_mag/niker/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView

from .forms import OrderForm
from .models import Shoes


# menu = [
#     {'title': 'Отзывы', 'url_name': 'home'}
# ]



class ShoesView(ListView):
    model = Shoes
    template_name = 'niker/index.html'
    
    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['menu'] = menu
    #     return context


class ShoesDetail(DetailView):
    model = Shoes
    template_name = 'niker/shoes_detail.html'
    slug_field = 'slug'


class CategoryView(ListView):
    model = Shoes
    template_name = 'niker/category_filter_views.html'

    def get_queryset(self):
        return Shoes.objects.filter(category__slug=self.kwargs['slug'])

class Search(ListView):

    template_name = 'niker/category_filter_views.html'

    def get_queryset(self):
        return Shoes.objects.filter(title__icontains=self.request.GET.get('q'))


class AddOrder(View):
    def post(self, request, pk):
        form = OrderForm(request.POST)
        shoes = Shoes.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.shoes = shoes
            form.save()
        return redirect(shoes.get_absolute_url())


class FilterShoes(ListView):
    template_name = 'niker/category_views.html'

    def get_queryset(self):
        queryset = Shoes.objects.filter(
            Q(color=self.request.GET.getlist('color'))
        )
        return queryset

shoes_mag/niker/templates/niker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{%static 'niker/css/base.css'%}"> 
    <link rel="stylesheet" href="{%  static 'niker/slick/slick.css' %}">
    <link rel="stylesheet" href="{%  static 'niker/slick/slick-themes.css' %}">
</head>
<body>
    <div class="container">
        {% include 'niker/include/header.html' %}
        
        {% block category %}
        {% endblock category %}

        {% block shoes_detail %}
        {% endblock %}

        {% block last_added %}
        {% endblock %}

        {% block filter_category %}
        {% endblock %}

    </div>


    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>    
    <script type="text/javascript" src="{% static 'niker/slick/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'niker/js/index.js' %}"></script>
</body>
</html>

shoes_mag/niker/templates/niker/category_filter_views.html
{% extends 'niker/base.html' %}
{% include 'niker/include/header.html' %}


{% block filter_category %}


<div class="shoes-section">
    {% for shoes in shoes_list %}
    <div class="shoes">
        <div class="shoes-image_section">
            <img src="{{shoes.img.url}}" alt="">
        </div>
        
        <div class="shoes-title_section">
            <h2 class="shoes-title-section_text">
                <a href="{{shoes.get_absolute_url}}">
                    {{shoes.title}}
                </a>
            </h2>
        </div>
    </div>
    {% endfor %}
</div>
    


{% endblock %}

shoes_mag/niker/templates/niker/include/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header_menu">
                <div class="header_logo">
                    <a href="{% url 'home' %}" class="header_logo-link">
                        <h1 class="header_logo-text">LUX CROSS</h1>
                    </a>
                </div>
                <div class="header_favorite-img">
                    <a href="#" class="header_favorite_img-link">
                        <img src="{% static 'niker/img/favorite-heart.svg' %}" alt="" class="header_favorite_img-logo">
                    </a>
                </div>
                <div class="header-search_section">
                    <form action="{% url 'search' %}" method="get">
                        {% csrf_token %}
                        <input type="search" placeholder="Название обуви" name="q">
                        <button type="submit" >Найти</button>
                    </form>
                </div>
                <div class="autorization-section">
                    <a href="" class="sign-in">
                        SIGN-IN
                    </a>
                    <a href="" class="register">
                        REGISTER
                    </a>
                </div>
            </div>
        </div>
    </header>
</body>
</html>

shoes_mag/niker/templates/niker/index.html
{% extends 'niker/base.html' %}
{% load category_tags %}
{% load last_added_tags %}

{% block category %}
    {%get_categories as categories%}
    <section class="category_section">
        <div class="category_wrapper">
            {%for category in categories%}
            <div class="category_title">
                <a href="{{category.get_absolute_url}}" class="category-title_link">
                    {{category.title}}
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

{% block last_added %}
{% get_last_added %}
{% endblock %}













































<!-- {% load static %}
{% load category_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'niker/css/index.css' %}"> 
    <link rel="stylesheet" href="{%  static 'niker/slick/slick.css' %}">
    <link rel="stylesheet" href="{%  static 'niker/slick/slick-theme.css' %}">

</head>
<body>
    <a href="{{shoes.get_absolute_url}}">{{shoes.title}}</a>
    {%get_categories as categories%}
    {%for category in categories%}
    <a href="{{category.get_absolute_url}}">{{category.title}}</a>
    {%endfor%}
    <h3 class="sear-head editContent">Пол</h3>
    <form action="{% url 'filter' %}">
        <ul class="w3layouts-box-list">
        {% for sex in view.get_sex %}
        <li class="editContent">
            <input type="checkbox" class="checked" name="sex" value="{{ sex.id }}">
            <span class="span-editContent">{{sex.title}}</span>
        </li>
        {% endfor %}
        </ul>
        <button type="submit">Фильтровать</button>
    </form>
    <form action="{% url 'search' %}" method="get">
        <input type="search" name="q">
        <button type="submit">Найти</button>
    </form>

    <div class="slider">
        {%for shoes in shoes_list %}
        <div class="slide">
            <div class="name">{{shoes.title}}</div>
            <div class="price">3500</div>
        </div>
        {% endfor %}
    </div>




    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>    
    <script type="text/javascript" src="{% static 'niker/slick/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'niker/js/main.js' %}"></script>

</body>
</html> -->

shoes_mag/niker/templates/niker/shoes_detail.html
{% extends 'niker/base.html' %}

{% block shoes_detail %}

<div class="desk">
    <div class="left">
        <div class="shoes-detail_section">
            <div class="shoes-detail-section_image">
                <img src="{{shoes.img.url}}" alt="" class="shoes-detail-section_img">
            </div>
            <div class="shoes-detail_model">
                <p class="shoes-detail-model_title">
                    Название модели: {{shoes.title}}
                </p>
            </div>
            <div class="shoes-detail-section_color">
                <p class="shoes-detail-section-color_text">Цвет:  {{shoes.color}}</p>
            </div>
            <div class="shoes-detail-section_size">
                <p class="shoes-detail-section-size_text">
                    Размеры:
                </p>
                <p class="shoes-detail-section_text_size">
                    {% for size in shoes.size.all %}
                     {{size.size}}
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
    <div class="right">
        <form action="{% url 'addorder' shoes.id %}" method="post">
            {%csrf_token%}
            <div class="add_order_name">
                <label for="username">Name</label>
                <input type="text" class="name"
                       name='name' id="username" required="">
            </div>
            <div class="add_order_number">
                <label for="usernumber">Number</label>
                <input type="text" class="number"
                       name='number' id="usernumber" required="">
            </div>
            <div class="address">
                <label for="useraddres">Addres</label>
                <input type="text" class="address"
                       name='address' id="useraddres" required="">
            </div>
            <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                Заказать
            </button>
        </form>
        <div class="extra-image_section">
            {% for image in shoes.shoesphoto_set.all %}
            <img src="{{image.img.url}}" alt="" class="extra-image-section_img">
            {%endfor%}
        </div>
    </div>
</div>

{% endblock %}


    <!-- <h2>{{shoes.title}}</h2>
    <form action="{% url 'addorder' shoes.id %}" method="post" class="mt-4">
        {% csrf_token %}
        <div class="username">
            <label for="username">Name</label>
            <input type="text" class="form-control border"
                   name='name' id="username" required="">
        </div>
        <div class="number">
            <label for="usernumber">Number</label>
            <input type="text" class="form-control border"
                   name='number' id="usernumber" required="">
        </div>
        <div class="place">
            <label for="useraddres">Addres</label>
            <input type="text" class="form-control border"
                   name='get_product_place' id="useraddres" required="">
        </div>
        <button type="submit"
                class="mt-3 btn btn-success btn-block py-3">
            Отправить
        </button>
    </form> -->

shoes_mag/niker/templates/niker/tags/last_added_shoes.html
{% load static %}
<section class="last_added">
    <h3 class="last-added_title">Последние новинки</h3>
    <div class="last-added-shoes_slider">
        {% for shoes in last_shoes %}
        <div class="slide">
            <div class="last-added-shoes_images">
                <img src="{{shoes.img.url}}" alt="" class="last-added-shoes_img">
            </div>
            <div class="last-added-shoes_title">
                <a href="{{shoes.get_absolute_url}}" class="last-added-shoes_link">
                    {{shoes.title}}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</section>